### ISSUE TITLE
Read more configuration.json files

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-agent#106]
We should use https://github.com/goraz/onion to read more configuration files with layers.

**Comment by amreo** [comment]
I think this issue is important and it should be done as soon as possible

**Comment by cirelli94** [comment]
Is there a list of file ordered by priority to close this issue?

**Comment by amreo** [comment]
Yes, and I think they are:
- /opt/ercole-agent/config.json
- /usr/share/ercole-agent/config.json
- /etc/ercole-agent/ercole-agent.json
- /etc/ercole-agent/conf.d/*.json
- ./config.json

**Comment by amreo** [comment]
On windows where should the files found the configs? @raffaelloferrari  @cirelli94  @danilopala

**Comment by raffaelloferrari** [comment]
On installation agent folder I think

**Comment by amreo** [comment]
Only in the agent directory??
