### ISSUE TITLE
 Add Oracle pluggable database support

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-agent#110]
If dbversion < 11.2.0.4 run as it's today, else:

fetcher(checkpdb)
    false -> normal execution
    true -> {

run listpdbs:
CDB|PDB
PIPPO|PDB1
PIPPO|PDB2
PIPPO|PDB3

foreach pdb in listpdbs:
    tablespace_pdb
    schema_pdb
}

create new pluggable databases field in HostData

**Comment by raffaelloferrari** [comment]
I decided to modify the listpdb structure:

PDB|OPEN_MODE
PDB1|READ WRITE
PDB2|MOUNTED
PDB3|MOUNTED 
...

**Comment by amreo** [comment]
@raffaelloferrari How can I know the list of pdbs of a CDB?

**Comment by raffaelloferrari** [comment]
@amreo you can execute query listpdb.sql
