### ISSUE TITLE
Merge ercole-agent-virtualization

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-agent#125]

**Comment by cirelli94** [comment]
To merge ercole-agent-virt I need to choose a criteria to run the "builder" virtualization.
Is it ok if a criteria I use the presence of parameter "hypervisors" in config.toml?

@raffaelloferrari @amreo

**Comment by amreo** [comment]
We have already discussed about this issue! Do you remember this thing?

```
Features: {
  "Databases": { "Enabled": true },
  "Exadata": { "Enabled": true, "NotRootUser": "ercole" },
}
```

**Comment by cirelli94** [comment]
That was for exadata!

We can add something like:

```
Features: {
  "Databases": { "Enabled": true },
  "Exadata": { "Enabled": true, "NotRootUser": "ercole" },
  "Virtualization": { "Enabled": true, "Hypervisors": [...] }
}
```
?

**Comment by amreo** [comment]
Yes
