### ISSUE TITLE
Change serverurl in settings

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-agent#139]
Instead of parameter 
 ```
     "serverurl": "http://localhost:9080/host/update",
```
in [config](https://github.com/ercole-io/ercole-agent/blob/master/config.json), we should have:
```
     "serverurl": "http://localhost",
     "serverport": "443",
```
and call the correct api inside ercole-agent

**Comment by amreo** [comment]
Why?

**Comment by cirelli94** [comment]
- It seems that in production sometimes they have problem because of some more "/": we can construct the path to check any missing or unwanted slash, it has no costs to us and it improve the usability: it's not pleasant to run ercole-agent for 30' and discover that it fails only for a wrong path in configuration. Now that you make me think about this, we should maybe check serverurl and port at start of ercole-agent!
- "serverurl" should be the server url, not an API!
- Today we only call one api: this api; one day we'll call some others: maybe if we want to create a new dedicated api for cluster we will need to call the server on another api: so we'll need it.

**Comment by cirelli94** [comment]
Already done.
