### ISSUE TITLE
Embed scripts and sql inside agent

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-agent#157]
Embed scripts and sql inside agent to avoid problem when updating.

We must add an option to save this files on filesystem.
We must add an option to use alternatively scripts and sql files from filesystem.

Here a proposal to embed files in build https://github.com/golang/go/issues/35950 with some libraries to do so.

**Comment by amreo** [comment]
Executing a single fetcher is a common use case for us.

**Comment by anbrenna** [comment]
We evaluated that it's not needed.
