### ISSUE TITLE
[BUG] Agent doesn't detect Oracle STD or ENT licenses when db is mounted

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole-agent#209]
**Describe the bug**
Agent doesn't detect Oracle STD or ENT licenses when db is in state mounted

**Expected behavior**
Agent should detect it anyway.

**To Reproduce**
Run the agent on a server with Oracle DB mounted

**Comment by amreo** [comment]
This isn't a proper bug report!

**Comment by cirelli94** [comment]
I beg you pardon, it was an already well known bug affecting v1 that we already fixed in v2, I already fixed it and release a new version with the fix.
