### ISSUE TITLE
Automatic start after machine's reboot

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-agent#277]
Add permanent behaviour in order to automatic restart the agent upon reboot of a machine

**Comment by amreo** [comment]
Isn't it already present with systemd? e.g 'systemctl enable ercole-agent`

**Comment by raffaelloferrari** [comment]
In version 1.x of ercole it was present through systemd from version 2.x I have no evidence that it is present in the code of ercole.

**Comment by amreo** [comment]
@cirelli94 ???

**Comment by cirelli94** [comment]
Agent already start at machine's reboot!
