### ISSUE TITLE
Add check for duplicated oratab entries

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-agent#309]
Add check for duplicated oratab entries, remove duplicated data and log a warning.
Modify the common_builder/oracle_databases.go file.

**Comment by cirelli94** [comment]
After we have retrieved oratabEntries here https://github.com/ercole-io/ercole-agent/blob/fe6258899151c283210693f36778b8ed964279f9/builder/common_builder/oracle_databases.go#L35-L39
We must check that `oratabEntries` `DBName` value is unique.
If not: remove duplicates and log a warning.
