### ISSUE TITLE
ERR: "Can't parse value" in Ercole agent

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-agent#474]
If "" is returned for the number of partitioned tables , ercole agent traces the following error:
ercole-agent[146236]: * /root/project/marshal/oracle/partitionings.go:49 : 'Can't parse value "" as int; err: strconv.Atoi: parsing "": invalid syntax'

**Comment by afumagalli98** [comment]
The stdout is empty so the agent can't parse the value as int. The agent's behavior is correct, closing the issue.
