### ISSUE TITLE
Windows: allow spaces into the installation path

### ISSUE THREAD

**Issue by simonerota** [ercole-io/ercole-agent#54]
Currently the windows version of the agent needs to be installed on paths that do not contain spaces. If the path contains spaces, the powershell fetcher is not launched correctly.

**Comment by amreo** [comment]
https://github.com/golang/go/issues/17149
http://daviddeley.com/autohotkey/parameters/parameters.htm#WIN

**Comment by cbiglioli** [comment]
Seems solved with: https://github.com/ercole-io/ercole-agent/issues/186
