### ISSUE TITLE
Verify behaviour of sar_cpu_only_linux.sh

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-agent#557]
The result of sar_cpu_only_linux.sh execution contains some negative values:
-1.06
.12
.12
-5.00
.13
.16
.09
.14

Verify the meaning of negative values and decide how to manage these kind of values

**Comment by SebastianoRotaSorint** [comment]
Fixed, in case of host restart only the last average will be considered (same way of thinking also applied to sar_disks_only_linux.sh)
