### ISSUE TITLE
Package for Linux Debian doesn't work properly

### ISSUE THREAD

**Issue by anbrenna** [ercole-io/ercole-agent#579]
Installation on Linux Debian failed with these errors:
useradd: group 'oinstall' does not exist
useradd: group 'dba' does not exist
useradd: group 'oinstall' does not exist
useradd: group 'mysql' does not exist

Solution: 
Befor adding the user to a group, check whether the group exists. If the group does not exist, the user must not be added.

**Comment by afumagalli98** [comment]
not resolved
